spring.application.name=datn demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=kitchef;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1234$
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


## Giúp Spring hi?u ??nh d?ng ngày tháng mà không b? l?i
#spring.jackson.serialization.write-dates-as-timestamps=false
# ??m b?o BigDecimal không b? m?t ?? chính xác khi truy?n qua JSON
spring.jackson.generator.write_bigdecimal_as_plain=true

# Ch?n vi?c Jackson t? ??ng truy xu?t các thu?c tính l?ng nhau n?u không c?n thi?t
spring.jackson.serialization.fail-on-empty-beans=false